import { createClient } from "npm:@supabase/supabase-js@2";
const VERSION="2026-08-23",BUCKET="lms-documents",MAX=25*1024*1024;
const env=(n:string)=>Deno.env.get(n)?.trim()||"";
function admin(){const url=env("SUPABASE_URL");let key=env("SUPABASE_SERVICE_ROLE_KEY");if(!key){try{key=JSON.parse(env("SUPABASE_SECRET_KEYS")||"{}").default||""}catch{}}if(!url||!key)throw Error("LMS server configuration is unavailable.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
const origins=new Set(["https://training.screenings4u.com","http://127.0.0.1:5500","http://localhost:5500"]);
const cors=(r:Request)=>({"Access-Control-Allow-Origin":origins.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://training.screenings4u.com","Vary":"Origin","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"});
const reply=(r:Request,b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json"}});
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));
const safe=(v:any)=>String(v||"file").replace(/[^a-zA-Z0-9._-]/g,"_");

const LOGO_URL="https://rgsrubdtljyxmnihwlah.supabase.co/storage/v1/object/public/branding/logo.png";
const emailShell=(eyebrow:string,title:string,content:string)=>`<!doctype html><html><body style="margin:0;background:#eef3f8;font-family:Arial,sans-serif;color:#263246"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef3f8"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:600px;max-width:100%;background:#fff;border:1px solid #dce5ef;border-radius:12px;overflow:hidden"><tr><td style="padding:24px 34px;border-bottom:4px solid #ff6b00"><img src="${LOGO_URL}" alt="screenings4u" width="220" style="display:block;width:220px;max-width:100%;height:auto"></td></tr><tr><td style="padding:34px"><div style="color:#ff6b00;font-size:12px;font-weight:800;letter-spacing:.1em;margin-bottom:9px">${eyebrow}</div><h1 style="margin:0 0 20px;color:#173d78;font-size:28px;line-height:1.2">${title}</h1>${content}</td></tr><tr><td style="padding:20px 34px;background:#173d78;color:#dce7f6;font-size:12px;line-height:1.6">screenings4u Learning Center<br>Need help? <a href="mailto:support@screenings4u.com" style="color:#fff">support@screenings4u.com</a></td></tr></table></td></tr></table></body></html>`;

const types=new Set(["application/pdf","image/png","image/jpeg","image/webp","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
const bytes=(v:any)=>{const x=String(v||"").replace(/^data:[^,]+,/,"");return x?Uint8Array.from(atob(x),c=>c.charCodeAt(0)):new Uint8Array()};
async function adminEmails(db:any){const out=new Set<string>();const configured=env("ADMIN_ORDER_EMAIL");if(configured)configured.split(/[;,]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(x=>out.add(x));const a=await db.from("user_role_assignments").select("user_id").eq("role","super_admin");if(!a.error&&a.data?.length){const ids=a.data.map((x:any)=>x.user_id);const p=await db.from("user_profiles").select("email").in("id",ids).eq("is_active",true);if(!p.error)(p.data||[]).forEach((x:any)=>x.email&&out.add(String(x.email).toLowerCase()))}if(!out.size)out.add("aerving@screenings4u.com");return [...out]}
async function mail(db:any,subject:string,body:string,key:string){const api=env("RESEND_API_KEY");if(!api){console.warn("RESEND_API_KEY missing");return}const to=await adminEmails(db);const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${api}`,"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({from:env("RESEND_FROM_EMAIL")||"screenings4u <notifications@screenings4u.com>",to,reply_to:"support@screenings4u.com",subject,html:body})});if(!r.ok)console.error("Admin email failed",await r.text())}
async function userFor(req:Request,db:any){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return {error:"Sign in is required."};const x=await db.auth.getUser(token);return x.error||!x.data.user?{error:x.error?.message||"Sign in is required."}:{user:x.data.user}}
async function enrollment(db:any,userId:string,eid:string){const e=await db.from("lms_enrollments").select("id,course_id,lms_courses(title)").eq("id",eid).eq("user_id",userId).single();return e}
async function notifyUpload(db:any,user:any,e:any,ld:any,name:string){const p=await db.from("user_profiles").select("display_name,email,first_name,last_name").eq("id",user.id).maybeSingle();const course:any=Array.isArray(e.data.lms_courses)?e.data.lms_courses[0]:e.data.lms_courses;const learner=p.data?.display_name||[p.data?.first_name,p.data?.last_name].filter(Boolean).join(" ")||p.data?.email||user.email||"Learner";await mail(db,`DOT mock training document uploaded — ${learner}`,emailShell("DOCUMENT UPLOAD","New DOT mock training document",`<p style="font-size:16px;line-height:1.65"><strong>${esc(learner)}</strong> uploaded <strong>${esc(name)}</strong> for <strong>${esc(course?.title||"DOT training")}</strong>.</p><p style="font-size:16px;line-height:1.65">The document is ready for admin review in the Learning Center.</p>`),`mock-${ld.data.id}`)}
async function createMockRecord(db:any,user:any,e:any,eid:string,path:string,name:string,mime:string,size:number){const exists=await db.from("documents").select("id").eq("storage_bucket",BUCKET).eq("storage_path",path).maybeSingle();if(exists.data){const prior=await db.from("lms_learner_documents").select("*").eq("document_id",exists.data.id).eq("user_id",user.id).maybeSingle();if(prior.data)return prior.data}
 const d=await db.from("documents").insert({owner_user_id:user.id,document_type:"lms_mock_training",title:name||"DOT Mock Training Documentation",description:"Learner-submitted DOT mock training documentation for certificate review.",storage_bucket:BUCKET,storage_path:path,mime_type:mime,file_size:size,is_confidential:true,visibility:"private",metadata:{source:"training_portal",enrollment_id:eid,course_id:e.data.course_id}}).select().single();if(d.error)throw Error(`Document record failed: ${d.error.message}`);const ld=await db.from("lms_learner_documents").insert({user_id:user.id,enrollment_id:eid,document_id:d.data.id,category:"mock_training",status:"submitted",uploaded_by:user.id}).select().single();if(ld.error)throw Error(`Learner document record failed: ${ld.error.message}`);await notifyUpload(db,user,e,ld,name);return ld.data}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return reply(req,{error:"Method not allowed"},405);try{const db=admin();const auth=await userFor(req,db);if(auth.error)return reply(req,{error:auth.error},401);const user=auth.user;const b=await req.json().catch(()=>({}));const a=String(b.action||"");
if(a==="status"){const q=await db.from("lms_onboarding_consents").select("*").eq("user_id",user.id).eq("consent_version",VERSION).maybeSingle();if(q.error)throw Error(`Onboarding query failed: ${q.error.message}`);const d=await db.from("lms_learner_documents").select("id").eq("user_id",user.id).eq("category","onboarding_acknowledgment").limit(1).maybeSingle();if(d.error)throw Error(`Onboarding document query failed: ${d.error.message}`);return reply(req,{consent:q.data||null,hasDocument:!!d.data})}
if(a==="enrollments"){const q=await db.from("lms_enrollments").select("id,course_id,status,progress_percent,expires_at,enrolled_at,lms_courses(title)").eq("user_id",user.id).order("enrolled_at",{ascending:false});if(q.error)throw Error(`Enrollment query failed: ${q.error.message}`);return reply(req,{enrollments:q.data||[]})}
if(a==="consent"){const first=String(b.firstName||"").trim(),last=String(b.lastName||"").trim(),email=String(b.email||"").trim().toLowerCase(),phone=String(b.phone||"").trim();if(!first||!last||!email)return reply(req,{error:"First name, last name, and email are required."},400);if(!b.acceptedTerms||!b.acceptedRefund||!b.acceptedDisclaimer||!b.acceptedMock)return reply(req,{error:"All four acknowledgments are required."},400);const pdf=bytes(b.acknowledgmentPdf);if(!pdf.length)return reply(req,{error:"The onboarding acknowledgment PDF could not be generated. Refresh the page and submit again."},400);const q=await db.from("lms_onboarding_consents").upsert({user_id:user.id,consent_version:VERSION,first_name:first,last_name:last,email,phone:phone||null,accepted_terms:true,accepted_refund_policy:true,accepted_disclaimer:true,accepted_mock_requirements:true,acceptance_snapshot:{source:"training_portal",version:VERSION},user_agent:req.headers.get("user-agent"),accepted_at:new Date().toISOString()},{onConflict:"user_id,consent_version"}).select().single();if(q.error)throw Error(`Onboarding save failed: ${q.error.message}`);let link:any=null;const old=await db.from("lms_learner_documents").select("id,document_id").eq("user_id",user.id).eq("category","onboarding_acknowledgment").limit(1).maybeSingle();if(old.data){link=old.data}else{const path=`learners/${user.id}/onboarding/${VERSION}/learning-center-onboarding-acknowledgment.pdf`;const up=await db.storage.from(BUCKET).upload(path,pdf,{contentType:"application/pdf",upsert:true});if(up.error)throw Error(`Onboarding PDF upload failed: ${up.error.message}`);const d=await db.from("documents").insert({owner_user_id:user.id,document_type:"lms_onboarding_acknowledgment",title:"Learning Center Onboarding Acknowledgment",description:"Signed Learning Center onboarding and policy acknowledgment.",storage_bucket:BUCKET,storage_path:path,mime_type:"application/pdf",file_size:pdf.length,is_confidential:true,visibility:"private",metadata:{source:"training_portal",consent_version:VERSION,consent_id:q.data.id}}).select().single();if(d.error)throw Error(`Onboarding document record failed: ${d.error.message}`);const ld=await db.from("lms_learner_documents").insert({user_id:user.id,document_id:d.data.id,category:"onboarding_acknowledgment",status:"accepted",uploaded_by:user.id}).select().single();if(ld.error)throw Error(`Onboarding document link failed: ${ld.error.message}`);link=ld.data}const learner=`${first} ${last}`.trim();await mail(db,`Learning Center onboarding completed — ${learner}`,emailShell("LEARNER ONBOARDING","Onboarding completed",`<p style="font-size:16px;line-height:1.65"><strong>${esc(learner)}</strong> (${esc(email)}) completed Learning Center onboarding.</p><p style="font-size:16px;line-height:1.65">The signed acknowledgment is stored in Documents.</p>`),`onboarding-${q.data.id}-${q.data.accepted_at}`);return reply(req,{consent:q.data,document:link})}
if(a==="list"){const q=await db.from("lms_learner_documents").select("id,category,status,admin_notes,created_at,enrollment_id,documents(id,title,description,mime_type,file_size,created_at,metadata)").eq("user_id",user.id).order("created_at",{ascending:false});if(q.error)throw Error(`Document list failed: ${q.error.message}`);return reply(req,{documents:q.data||[]})}
if(a==="signed"){const q=await db.from("lms_learner_documents").select("documents(storage_bucket,storage_path,title)").eq("id",String(b.id||"")).eq("user_id",user.id).single();if(q.error)return reply(req,{error:"Document not found."},404);const d:any=Array.isArray(q.data.documents)?q.data.documents[0]:q.data.documents;if(!d?.storage_bucket||!d?.storage_path)return reply(req,{error:"Document file is unavailable."},404);const s=await db.storage.from(d.storage_bucket).createSignedUrl(d.storage_path,300,{download:d.title||true});if(s.error)throw Error(`Download failed: ${s.error.message}`);return reply(req,{url:s.data.signedUrl})}
if(a==="prepare_mock_upload"){const eid=String(b.enrollmentId||""),f=b.file||{},mime=String(f.mimeType||""),size=Number(f.size||0);const e=await enrollment(db,user.id,eid);if(e.error)return reply(req,{error:"Choose one of your enrolled courses."},404);if(!types.has(mime))return reply(req,{error:"Upload PDF, Word, JPG, PNG, or WebP."},400);if(!size||size>MAX)return reply(req,{error:"Each file must be 25 MB or smaller."},400);const path=`learners/${user.id}/mock-training/${eid}/${Date.now()}-${crypto.randomUUID()}-${safe(f.name)}`;const s=await db.storage.from(BUCKET).createSignedUploadUrl(path);if(s.error)throw Error(`Unable to prepare upload: ${s.error.message}`);return reply(req,{bucket:BUCKET,path,token:s.data.token})}
if(a==="finalize_mock_upload"){const eid=String(b.enrollmentId||""),path=String(b.path||""),f=b.file||{},mime=String(f.mimeType||""),name=String(f.name||"DOT Mock Training Documentation"),size=Number(f.size||0);const prefix=`learners/${user.id}/mock-training/${eid}/`;if(!path.startsWith(prefix))return reply(req,{error:"Invalid upload path."},400);const e=await enrollment(db,user.id,eid);if(e.error)return reply(req,{error:"Choose one of your enrolled courses."},404);if(!types.has(mime)||!size||size>MAX)return reply(req,{error:"The uploaded file is not valid."},400);const folder=path.slice(0,path.lastIndexOf('/')),fileName=path.slice(path.lastIndexOf('/')+1);const listed=await db.storage.from(BUCKET).list(folder,{search:fileName,limit:10});if(listed.error)throw Error(`Upload verification failed: ${listed.error.message}`);const object=(listed.data||[]).find((x:any)=>x.name===fileName);if(!object)throw Error("Upload did not finish. Please try again.");const actual=Number(object.metadata?.size||size);if(actual>MAX)throw Error("The uploaded file exceeds 25 MB.");const ld=await createMockRecord(db,user,e,eid,path,name,mime,actual);return reply(req,{document:ld})}
if(a==="upload_mock"){const eid=String(b.enrollmentId||""),f=b.file||{};const e=await enrollment(db,user.id,eid);if(e.error)return reply(req,{error:"Choose one of your enrolled courses."},404);const mime=String(f.mimeType||"");if(!types.has(mime))return reply(req,{error:"Upload PDF, Word, JPG, PNG, or WebP."},400);const file=bytes(f.base64);if(!file.length||file.length>MAX)return reply(req,{error:"Each file must be 25 MB or smaller."},400);const path=`learners/${user.id}/mock-training/${eid}/${Date.now()}-${crypto.randomUUID()}-${safe(f.name)}`;const up=await db.storage.from(BUCKET).upload(path,file,{contentType:mime});if(up.error)throw Error(`Upload failed: ${up.error.message}`);const ld=await createMockRecord(db,user,e,eid,path,String(f.name||"DOT Mock Training Documentation"),mime,file.length);return reply(req,{document:ld})}
return reply(req,{error:"Unknown action."},400)}catch(e){console.error("lms-learner-documents",e);return reply(req,{error:e instanceof Error?e.message:String(e)},500)}});
